apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-deployment
  template:
    metadata:
      labels:
        app: command-deployment
    spec:
      containers:
        - name: command-deployment
          image: guilhermelinosp/command.service.api:latest
          ports:
            - containerPort: 8081