apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-service-api
  template:
    metadata:
      labels:
        app: platform-service-api
    spec:
      containers:
        - name: platform-service-api
          image: guilhermelinosp/platform.service.api:latest
