apiVersion: v1
kind: Service
metadata:
  name: platform-cluster
spec:
  type: ClusterIP
  selector:
    app: platform-service-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: grpc
      protocol: TCP
      port: 666
      targetPort: 666