apiVersion: v1
kind: Service
metadata:
  name: platform-nodeport
spec:
  type: NodePort
  selector:
    app: platform-service-api
  ports:
    - name: platform-service-api
      protocol: TCP
      port: 80
      targetPort: 80
