name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [Command, Platform]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Set service_lowercase
        id: set_service_lowercase
        run: echo "::set-output name=service_lowercase::$(echo ${{ matrix.service }} | tr '[:upper:]' '[:lower:]')"

      - name: Build and Push Dockerfile for ${{ matrix.service }} Service API to Docker Hub
        run: |
          docker build -t ${{ steps.set_service_lowercase.outputs.service_lowercase }}.service.api:dev -f ./Source/${{ matrix.service }}/${{ matrix.service }}.Service.API/Dockerfile .
          docker push ${{ steps.set_service_lowercase.outputs.service_lowercase }}.service.api:dev
