name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [Command, Platform]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Service Lowercase
        id: set_service_lowercase
        run: |
          service_lowercase=$(echo ${{ matrix.service }} | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=service_lowercase::$service_lowercase"

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Source/${{ matrix.service }}/${{ matrix.service }}.Service.API/Dockerfile
          push: true
          tags: |
            ${{ github.actor }}/${{ steps.set_service_lowercase.outputs.service_lowercase }}.service.api:latest

      - name: Build and Push Docker Image
        uses: GlueOps/github-actions-build-push-containers@v0.3.5
        with:
          dockerfile: ./Source/${{ matrix.service }}/${{ matrix.service }}.Service.API/Dockerfile
          registry: ghcr.io
          registry-username: ${{ github.actor }}
          image_name: ${{ github.actor }}/${{ steps.set_service_lowercase.outputs.service_lowercase }}.service.api
          context: .
          target_directory: .
          tags: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
