name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [command, platform]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build the Docker image for ${{ matrix.service }} Service API
        run: docker build -t ${{ matrix.service }}.service.api:$(date +%s) ./Source/${{ matrix.service }}/Service.API

      - name: Docker Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker Image
        run: |
          docker push ${{ matrix.service }}.service.api:$(date +%s)
