name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [Command, Platform]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Push Docker image for ${{ matrix.service }} Service API
        run: |
          docker build -t ${{ matrix.service.toLowerCase() }}.service.api:$(date +%s) -f ./Source/${{ matrix.service }}/${{ matrix.service }}.Service.API/Dockerfile .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ matrix.service.toLowerCase() }}.service.api:$(date +%s)
