on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [Command, Platform]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.7.0 # Use the latest available version

      - name: Set service_lowercase
        id: set_service_lowercase
        run: |
          echo "Setting lowercase service name..."
          service_lowercase=$(echo ${{ matrix.service }} | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=service_lowercase::${service_lowercase}"
          echo "Lowercase service name set to: ${service_lowercase}"

      - name: Build and Push Dockerfile for ${{ matrix.service }} Service API
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_IMAGE: ./Source/${{ matrix.service }}/${{ matrix.service }}.Service.API/Dockerfile
        run: |
          echo "Logging into Docker registry..."
          echo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          echo "Docker login successful."

          echo "Creating and inspecting Docker Buildx builder..."
          docker buildx create --use || exit 1
          docker buildx inspect --bootstrap || exit 1

          echo "Building and pushing Docker image for ${{ matrix.service }} Service API..."
          docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_IMAGE . || exit 1
          docker push $DOCKER_IMAGE || exit 1
          echo "Docker image successfully built and pushed."
