on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [Command, Platform]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.7.0

      - name: Set service_lowercase
        id: set_service_lowercase
        run: |
          echo "Setting lowercase service name..."
          service_lowercase=$(echo ${{ matrix.service }} | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=service_lowercase::${service_lowercase}"
          echo "Lowercase service name set to: ${service_lowercase}"

      - name: Build and Push Dockerfile for ${{ matrix.service }} Service API
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_REPOSITORY: guilhermelinosp  # Substitua pelo seu nome de usuário ou organização no Docker Hub
          DOCKER_SERVICE: ${{ matrix.service }}
          DOCKER_IMAGE_TAG: dev
        run: |
          echo "Logging into Docker registry..."
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_REPOSITORY || exit 1
          echo "Docker login successful."

          echo "Creating and inspecting Docker Buildx builder..."
          docker buildx create --use || exit 1
          docker buildx inspect --bootstrap || exit 1

          DOCKER_IMAGE="${DOCKER_REPOSITORY}/${DOCKER_SERVICE}-api:${DOCKER_IMAGE_TAG}"

          echo "Building and pushing Docker image for $DOCKER_SERVICE Service API..."
          docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_IMAGE -f ./Source/${DOCKER_SERVICE}/${DOCKER_SERVICE}.Service.API/Dockerfile . --push || exit 1
          echo "Docker image successfully built and pushed."
