name: GitHub Packages CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [Command, Platform]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set service_lowercase
        id: set_service_lowercase
        run: echo "::set-output name=service_lowercase::$(echo ${{ matrix.service }} | tr '[:upper:]' '[:lower:]')"

      - name: Docker Login to GitHub Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin


      - name: Build and push Docker images to GitHub Packages
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: ./Source/${{ matrix.service }}/${{ matrix.service }}.Service.API/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ secrets.DOCKER_REGISTRY }}/${{ steps.set_service_lowercase.outputs.service_lowercase }}.service.api:dev
