name: GitHub Packages CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [Command, Platform]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set service_lowercase
        id: set_service_lowercase
        run: echo "::set-output name=service_lowercase::$(echo ${{ github.event_name }} | tr '[:upper:]' '[:lower:]')"

      - name: Docker Login to GitHub Packages
        uses: docker/login-action@v2.1.0
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

